### ISSUE TITLE
4/8-4/14 When to gym?

### ISSUE THREAD

**Issue by yingren-wang** [dead-programmer/HANG-out#2]
### Morning Gym Suggested
10PM: time home
10:30PM: time to sleep 
6AM: time to get up
6:30-8AM: gym time

**Comment by yingren-wang** [comment]
### Analysis
Total hours of sleep: 7-7.5h
Total hours of gym: 1-1.5h
Rating: even better than your normal day schedule

**Comment by blakepennington97** [comment]
Problem: Waking up at 6 AM

**Comment by pranmar123** [comment]
problem: bubba takes 6:30 to 8 to drink protein shake

**Comment by yingren-wang** [comment]
> Problem: Waking up at 6 AM

**Comment change suggestion:**
Problem: Blake Pennington
