### ISSUE TITLE
4/8-4/14 Botanical Gardens still? <Ticket Price>

### ISSUE THREAD

**Issue by yingren-wang** [dead-programmer/HANG-out#3]
Ticket price to Botanical Gardens checked: 
$21 for 4/10, Wednesday, 5:30-9PM

Botanical Gardens still?

**Comment by blakepennington97** [comment]
Let's do Wednesday? The weather will be nicer + off gym day + same price ($21)

**Comment by yingren-wang** [comment]
@blakepennington97 Bug fixed, I meant 4/10, Wednesday.
Notes: Late night hours is not available for Tuesdays
