### ISSUE TITLE
4/8-4/14 Pizzelle's Confections on Wednesday?

### ISSUE THREAD

**Issue by yingren-wang** [dead-programmer/HANG-out#9]
Due to unpredictable bad weather on Monday, unpredictable frisbee activity led by enthusiasm, and predictable love towards frisbee showed in HANG out Gang vote, Pizzelle's Confections plan is sadly canceled for Tuesday, 4/9. The current concern is whether we gonna go to Pizzelle's Confections on **Wednesday, 4/10, before 6 PM** instead or **cancel** Pizzelle's Confections for the week of 4/8-4/14.

**Comment by blakepennington97** [comment]
Why are we solving 2+2 = 4 with calculus

**Comment by Jake-Cloud** [comment]
I vote for Wednesday

**Comment by yingren-wang** [comment]
> Why are we solving 2+2 = 4 with calculus

Because we are nerds

**Comment by blakepennington97** [comment]
> > Why are we solving 2+2 = 4 with calculus
> 
> Because we are nerds

🤓
